# permissions for end users to edit fleets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: loputoo
    app.kubernetes.io/managed-by: kustomize
  name: fleet-editor-role
rules:
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - fleets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - fleets/status
  verbs:
  - get
