# permissions for end users to view fleets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: loputoo
    app.kubernetes.io/managed-by: kustomize
  name: fleet-viewer-role
rules:
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - fleets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - fleets/status
  verbs:
  - get
