apiVersion: network.unfamousthomas.me/v1alpha1
kind: Fleet
metadata:
  labels:
    app.kubernetes.io/name: loputoo
    app.kubernetes.io/managed-by: kustomize
  name: fleet-sample
spec:
  min_replicas: 3
  spec:
    duration: 5m
    allowForceDelete: false
    pod:
      containers:
        - name: example-container
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
