apiVersion: network.unfamousthomas.me/v1alpha1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: loputoo
    app.kubernetes.io/managed-by: kustomize
  name: server-sample
spec:
  timeout: 5m
  allowForceDelete: false
  pod:
    containers:
      - name: example-container
        image: nginx:latest
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"

  # TODO(user): Add fields here
