apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "thesis-operator.fullname" . }}-fleet-viewer-role
  labels:
  {{- include "thesis-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - fleets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - fleets/status
  verbs:
  - get