apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "thesis-operator.fullname" . }}-gametype-editor-role
  labels:
  {{- include "thesis-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - gametypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - gametypes/status
  verbs:
  - get