apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "thesis-operator.fullname" . }}-manager-role
  labels:
  {{- include "thesis-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patcch
  - update
  - watch
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - fleets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - fleets/finalizers
  verbs:
  - update
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - fleets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - gameautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - gameautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - gameautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - gametypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - gametypes/finalizers
  verbs:
  - update
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - gametypes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - servers/finalizers
  verbs:
  - update
- apiGroups:
  - network.unfamousthomas.me
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "thesis-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "thesis-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "thesis-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "thesis-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'