name: Operator Unit Tests

on:
  pull_request:
    paths:
      - 'operator/**'
      - '.github/workflows/run-operator-unit-tests.yml' # re-run if workflow changes

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies and run tests
        working-directory: ./operator
        run: make test
