name: Operator Unit Tests

on:
  pull_request:
    paths-ignore:
      - 'operator/**'
      - '.github/workflows/test.yml' # re-run if workflow changes

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "No relevant changes detected."